/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfirmacionRouteImport } from './routes/confirmacion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelSlugRouteImport } from './routes/panel.$slug'
import { Route as DevEnrichmentPreviewRouteImport } from './routes/dev.enrichment-preview'
import { Route as DevDomainPreviewRouteImport } from './routes/dev.domain-preview'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiOpsWaOpenedRouteImport } from './routes/api.ops.wa-opened'
import { Route as ApiBrevoWebhookRouteImport } from './routes/api.brevo.webhook'

const ConfirmacionRoute = ConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelSlugRoute = PanelSlugRouteImport.update({
  id: '/panel/$slug',
  path: '/panel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEnrichmentPreviewRoute = DevEnrichmentPreviewRouteImport.update({
  id: '/dev/enrichment-preview',
  path: '/dev/enrichment-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDomainPreviewRoute = DevDomainPreviewRouteImport.update({
  id: '/dev/domain-preview',
  path: '/dev/domain-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsWaOpenedRoute = ApiOpsWaOpenedRouteImport.update({
  id: '/api/ops/wa-opened',
  path: '/api/ops/wa-opened',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrevoWebhookRoute = ApiBrevoWebhookRouteImport.update({
  id: '/api/brevo/webhook',
  path: '/api/brevo/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/dev/domain-preview': typeof DevDomainPreviewRoute
  '/dev/enrichment-preview': typeof DevEnrichmentPreviewRoute
  '/panel/$slug': typeof PanelSlugRoute
  '/api/brevo/webhook': typeof ApiBrevoWebhookRoute
  '/api/ops/wa-opened': typeof ApiOpsWaOpenedRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/dev/domain-preview': typeof DevDomainPreviewRoute
  '/dev/enrichment-preview': typeof DevEnrichmentPreviewRoute
  '/panel/$slug': typeof PanelSlugRoute
  '/api/brevo/webhook': typeof ApiBrevoWebhookRoute
  '/api/ops/wa-opened': typeof ApiOpsWaOpenedRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/dev/domain-preview': typeof DevDomainPreviewRoute
  '/dev/enrichment-preview': typeof DevEnrichmentPreviewRoute
  '/panel/$slug': typeof PanelSlugRoute
  '/api/brevo/webhook': typeof ApiBrevoWebhookRoute
  '/api/ops/wa-opened': typeof ApiOpsWaOpenedRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmacion'
    | '/dev/domain-preview'
    | '/dev/enrichment-preview'
    | '/panel/$slug'
    | '/api/brevo/webhook'
    | '/api/ops/wa-opened'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmacion'
    | '/dev/domain-preview'
    | '/dev/enrichment-preview'
    | '/panel/$slug'
    | '/api/brevo/webhook'
    | '/api/ops/wa-opened'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/confirmacion'
    | '/dev/domain-preview'
    | '/dev/enrichment-preview'
    | '/panel/$slug'
    | '/api/brevo/webhook'
    | '/api/ops/wa-opened'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmacionRoute: typeof ConfirmacionRoute
  DevDomainPreviewRoute: typeof DevDomainPreviewRoute
  DevEnrichmentPreviewRoute: typeof DevEnrichmentPreviewRoute
  PanelSlugRoute: typeof PanelSlugRoute
  ApiBrevoWebhookRoute: typeof ApiBrevoWebhookRoute
  ApiOpsWaOpenedRoute: typeof ApiOpsWaOpenedRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confirmacion': {
      id: '/confirmacion'
      path: '/confirmacion'
      fullPath: '/confirmacion'
      preLoaderRoute: typeof ConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/$slug': {
      id: '/panel/$slug'
      path: '/panel/$slug'
      fullPath: '/panel/$slug'
      preLoaderRoute: typeof PanelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/enrichment-preview': {
      id: '/dev/enrichment-preview'
      path: '/dev/enrichment-preview'
      fullPath: '/dev/enrichment-preview'
      preLoaderRoute: typeof DevEnrichmentPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/domain-preview': {
      id: '/dev/domain-preview'
      path: '/dev/domain-preview'
      fullPath: '/dev/domain-preview'
      preLoaderRoute: typeof DevDomainPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/wa-opened': {
      id: '/api/ops/wa-opened'
      path: '/api/ops/wa-opened'
      fullPath: '/api/ops/wa-opened'
      preLoaderRoute: typeof ApiOpsWaOpenedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brevo/webhook': {
      id: '/api/brevo/webhook'
      path: '/api/brevo/webhook'
      fullPath: '/api/brevo/webhook'
      preLoaderRoute: typeof ApiBrevoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmacionRoute: ConfirmacionRoute,
  DevDomainPreviewRoute: DevDomainPreviewRoute,
  DevEnrichmentPreviewRoute: DevEnrichmentPreviewRoute,
  PanelSlugRoute: PanelSlugRoute,
  ApiBrevoWebhookRoute: ApiBrevoWebhookRoute,
  ApiOpsWaOpenedRoute: ApiOpsWaOpenedRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
